# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 34e934c0a6a56bab908f4a8ffa2871c79610b3821474152504aacc5ba1d9bd75c3c1f831e5579a5dae173afa9dbb470bbec283f6fc0d87890d39b01894833ed9

test:
  secret_key_base: b6c7fd95bbc67553a6c83150bace6d340c6c3e7cb5b405f763cfe4b58a7381d29cf9e118f1916b732a90af241c37d2f39a8fc255a2b11f1bb409261f45a9bdb1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
